import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import HeroBanner from './components/header/HeroBanner'
import { Container, Row, Col,Navbar,Offcanvas,Nav} from 'react-bootstrap'
import Link from 'next/link'
import Button from 'react-bootstrap/Button';
import Card from 'react-bootstrap/Card';


import "swiper/css";
import "swiper/css/pagination";
import { Autoplay, Pagination, Navigation } from "swiper";
import { Swiper, SwiperSlide } from "swiper/react";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroBanner/>

      {/* Sản phẩm Sale */}
      <Container className='pt-5 pb-5'>
        <h2 className={styles.sale}>KHUYẾN MẠI THÁNG NÀY</h2>
        <div className='row'>
          <div className='col-6 col-md-3 p-0'>

          <Card className={styles.card}>
            <div  ><Card.Img variant="top" src="../home-img/sale1.jpg"  className={styles.img_sale} /></div>
            <Card.Body className='d-flex flex-column align-items-center justify-content-center'>
              <Card.Title> <div className={styles.name_products_sale}>Móc Chìa Khóa Kiêm Ví Mini - 6976</div></Card.Title>
              <Card.Text>
              <div className={styles.price}>350.000 VND</div>
              </Card.Text>
              <div className={styles.price_sale}> 250.000 VND</div>
              <button className={styles.btn_sale}>Mua ngay</button>
            </Card.Body>
          </Card>
          </div>

          <div className='col-6 col-md-3 p-0'>

          <Card className={styles.card}>
            <div  ><Card.Img variant="top" src="../home-img/sale2.jpg" className={styles.img_sale}  /></div>
            <Card.Body className='d-flex flex-column align-items-center justify-content-center'>
              <Card.Title> <div className={styles.name_products_sale}>Móc Chìa Khóa Kiêm Ví Mini - 6976</div></Card.Title>
              <Card.Text>
              <div className={styles.price}>350.000 VND</div>
              </Card.Text>
              <div className={styles.price_sale}> 250.000 VND</div>
              <button className={styles.btn_sale}>Mua ngay</button>
            </Card.Body>
          </Card>
          </div>

          <div className='col-6 col-md-3 p-0'>

          <Card className={styles.card}>
            <div  ><Card.Img variant="top" src="../home-img/sale3.jpg"  className={styles.img_sale} /></div>
            <Card.Body className='d-flex flex-column align-items-center justify-content-center'>
              <Card.Title> <div className={styles.name_products_sale}>Móc Chìa Khóa Kiêm Ví Mini - 6976</div></Card.Title>
              <Card.Text>
              <div className={styles.price}>350.000 VND</div>
              </Card.Text>
              <div className={styles.price_sale}> 250.000 VND</div>
              <button className={styles.btn_sale}>Mua ngay</button>
            </Card.Body>
          </Card>
          </div>

          <div className='col-6 col-md-3 p-0'>

          <Card className={styles.card}>
            <div  ><Card.Img variant="top" src="../home-img/sale4.jpg" className={styles.img_sale}  /></div>
            <Card.Body className='d-flex flex-column align-items-center justify-content-center'>
              <Card.Title> <div className={styles.name_products_sale}>Móc Chìa Khóa Kiêm Ví Mini - 6976</div></Card.Title>
              <Card.Text>
              <div className={styles.price}>350.000 VND</div>
              </Card.Text>
              <div className={styles.price_sale}> 250.000 VND</div>
              <button className={styles.btn_sale}>Mua ngay</button>
            </Card.Body>
          </Card>
          </div>

        </div>

        

        
      </Container>

      <Container className='p-5'>
        <div className='row'>
          <div className='col-12 col-md-6 p-0'>
              <div className={styles.image_collection}>
                <img src='../home-img/banner1.jpg' className={styles.img_banner}/>
                <h3 className={styles.title_banner}>BỘ SƯU TẬP DÀNH CHO NỮ</h3>
                <div className={styles.overlay}></div>
              </div>
          </div>
          <div className='col-12 col-md-6 p-0'>
              <div className={styles.image_collection}>
                <img src='../home-img/banner2.jpg' className={styles.img_banner}/>
                <h3  className={styles.title_banner}>BỘ SƯU TẬP DÀNH CHO NAM</h3>
                <div className={styles.overlay}></div>
              </div>
          </div>
        </div>
      </Container>

      <Container className='pt-5 pb-5'>
        <h2 className={styles.sale}>SẢN PHẨM BÁN CHẠY</h2>
        <div className='row'>
          <div className='col-6 col-md-3 p-0'>

          <Card className={styles.card}>
            <div  ><Card.Img variant="top" src="../home-img/sale1.jpg"  className={styles.img_sale} /></div>
            <Card.Body className='d-flex flex-column align-items-center justify-content-center'>
              <Card.Title> <div className={styles.name_products_sale}>Móc Chìa Khóa Kiêm Ví Mini - 6976</div></Card.Title>
              <Card.Text>
              <div className={styles.price}>350.000 VND</div>
              </Card.Text>
              <div className={styles.price_sale}> 250.000 VND</div>
              <button className={styles.btn_sale}>Mua ngay</button>
            </Card.Body>
          </Card>
          </div>

          <div className='col-6 col-md-3 p-0'>

          <Card className={styles.card}>
            <div  ><Card.Img variant="top" src="../home-img/sale2.jpg" className={styles.img_sale}  /></div>
            <Card.Body className='d-flex flex-column align-items-center justify-content-center'>
              <Card.Title> <div className={styles.name_products_sale}>Móc Chìa Khóa Kiêm Ví Mini - 6976</div></Card.Title>
              <Card.Text>
              <div className={styles.price}>350.000 VND</div>
              </Card.Text>
              <div className={styles.price_sale}> 250.000 VND</div>
              <button className={styles.btn_sale}>Mua ngay</button>
            </Card.Body>
          </Card>
          </div>

          <div className='col-6 col-md-3 p-0'>

          <Card className={styles.card}>
            <div  ><Card.Img variant="top" src="../home-img/sale3.jpg"  className={styles.img_sale} /></div>
            <Card.Body className='d-flex flex-column align-items-center justify-content-center'>
              <Card.Title> <div className={styles.name_products_sale}>Móc Chìa Khóa Kiêm Ví Mini - 6976</div></Card.Title>
              <Card.Text>
              <div className={styles.price}>350.000 VND</div>
              </Card.Text>
              <div className={styles.price_sale}> 250.000 VND</div>
              <button className={styles.btn_sale}>Mua ngay</button>
            </Card.Body>
          </Card>
          </div>

          <div className='col-6 col-md-3 p-0'>

          <Card className={styles.card}>
            <div  ><Card.Img variant="top" src="../home-img/sale4.jpg" className={styles.img_sale}  /></div>
            <Card.Body className='d-flex flex-column align-items-center justify-content-center'>
              <Card.Title> <div className={styles.name_products_sale}>Móc Chìa Khóa Kiêm Ví Mini - 6976</div></Card.Title>
              <Card.Text>
              <div className={styles.price}>350.000 VND</div>
              </Card.Text>
              <div className={styles.price_sale}> 250.000 VND</div>
              <button className={styles.btn_sale}>Mua ngay</button>
            </Card.Body>
          </Card>
          </div>

        </div>

        

        
      </Container>
      
    </>
  )
}
